### ISSUE TITLE
Backend-api-defination module Does not exist

### ISSUE THREAD

**Issue by sajal-halder** [ZaTribune/springboot-ddd-example#2]
In backend-infrastructure/pom.xml 
     <dependency>
            <groupId>com.tribune</groupId>
            <artifactId>backend-api-definition</artifactId>
        </dependency>

backend-api-definition module is not present . Can you add it?

**Comment by ZaTribune** [comment]
Sorry I've neglected this repo but I'll do it soon ISA.

**Comment by ZaTribune** [comment]
@sajal-halder I've added the api-definition module along with some notes:
* This module includes files generated by open-api.  
* Treated as part of the infrastructure layer.
* It's an optional feature, so there's no need to utilize it currently.  
---- It's not necessary at the moment, but you can see how it's implemented/considered in the project.
